### ISSUE TITLE
Выложите, пожалуйста всю книгу целиком в формате .pdf

### ISSUE THREAD

**Issue by DimitriBolt** [Pozdniakov/tidy_stats#1]
Ну или расскажите, как собрать всю книгу в .pdf. (я умею конвертировать один файл .rmd в .pdf, но как собрать всю книгу не знаю).
Спасибо.
З.Ы. Ещё лучше было бы иметь эту книгу в .fb2(epub), а то читать с читалки очень не удобно без этих форматов.

**Comment by DimitriBolt** [comment]
Нашёл, как конвертировать в epub.
![image](https://user-images.githubusercontent.com/37275623/195220319-c0bf1a8e-2b96-490c-bbdc-ff658726b99a.png)
счастье наступило, можно читать с читалкой на диване.
Upd. 
Нет, всё-таки встроенная конвертировалка делает это плохо. Хорошо бы тиеть уже готовый правльный EPUB.

**Comment by Pozdniakov** [comment]
Пофиксил, теперь работает загрузка и в epub, и в pdf
